# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'What is KinMS',  url: 'welcome-to-kinms'}
- {name: 'Installation & Tutorial', url: 'getting-started_wkinms'}
- {name: 'Documentation',      url: 'documentation'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/timdavisastro'}
- {icon: 'envelope', link:   '&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#68;&#97;&#118;&#105;&#115;&#84;&#64;&#99;&#97;&#114;&#100;&#105;&#102;&#102;&#46;&#97;&#99;&#46;&#117;&#107;'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Click here to share'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
